### ISSUE TITLE
Call to undefined function et_builder_enqueue_font()

### ISSUE THREAD

**Issue by ziodave** [Arsenal21/all-in-one-wordpress-security#84]
Hello,

When using a Divi child theme and the Login blocking feature, the "Request Unlock" page won't show because of the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function et_builder_enqueue_font() in [wordpress]/wp-content/themes/Divi/functions.php:195
Stack trace:
#0 [wordpress]/wp-includes/class-wp-hook.php(298): et_divi_load_scripts_styles('')
#1 [wordpress]/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 [wordpress]/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 [wordpress]/wp-includes/script-loader.php(1296): do_action('wp_enqueue_scri...')
#4 [wordpress]/wp-includes/class-wp-hook.php(298): wp_enqueue_scripts('')
#5 [wordpress]/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#6 [wordpress]/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 [wordpress]/wp-includes/general-template.php(2589): do_action('wp_head')
#8 [wordpress]/wp-content/plugins/all-in-one-wp-security-and-firewall/other-includes/wp-security-unlock-request.php(10): wp_head()
#9 [wordpress]/wp-content in [wordpress]/wp-content/themes/Divi/functions.php on line 195
```

**Comment by ziodave** [comment]
Now cross-posted on https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=716070
